# Python
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = {command = "ruff", args = ["format", "--quiet", "-"]}
auto-format = true

# Rust
[[language]]
name = "rust"
formatter = {command = "rustfmt"}

# QML
[language-server.qmlls]
command = "qmlls6"

[[language]]
name = "qml"
language-servers = ["qmlls"]

# Web
[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[[language]]
name = "svelte"
roots = ["package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "svelte", "biome" ]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "deno-lsp" ]

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "deno-lsp" ]

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
