[config]

# [config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = false

[templates.gtk3]
input_path = "./templates/gtk3.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "./templates/gtk4.css"
output_path = "~/.config/gtk-4.0/colors.css"
