#!/usr/bin/env bash

# --- VARIABLES ---

ROOT="$HOME/.dotfiles/Enabled/"
GIT="git --git-dir=$ROOT/.git --work-tree=$ROOT"
STOW="stow --dotfiles --dir=$ROOT --target=$HOME"

PACKAGES=$(find $ROOT -maxdepth 1 -mindepth 1 -type d -printf "%f ")

# --- FUNCTIONS ---

function show_usage {
	echo "Usage: stow-dots [help] [sync|push|both] [list] [fix] [install]"
}

function log {
	echo "> $1"
}

function log_error {
	log "ERROR: $1"
}

function list {
	ls $ROOT --group-directories-first --color
}

function sync {
	log "Sync."

	$STOW --no-folding $PACKAGES

	# Check if stow return error.
	if [ $? -ne 0 ]; then
		log_error "Stow threw a error."
		exit 1
	fi

	log "Sync completed."
}

function push {
	log "Start git."

	# Push to repository with Git.
	$GIT add .
	$GIT commit -m "Update"
	$GIT push

	# Check if Git return error.
	if [ $? -ne 0 ]; then
		log_error "Git threw a error."
		exit 1
	fi

	log "Push completed."
}

function both {
	sync
	echo ''
	push
}

function fix {
	log "Search and delete broken symlinks."
	find ${XDG_CONFIG_HOME:-$HOME/.config} -xtype l -delete
	find ${XDG_DATA_HOME:-$HOME/.local/share} -xtype l -delete
}

function install {
	fix
	log ''

	log "That will restow your dots to make a fresh install. You are sure of proceed? (s/N)"
	read INPUT
	log ''

	if [[ $INPUT = "s" || $INPUT = "S" ]]; then
		log "Installation started."

		$STOW --restow --no-folding $PACKAGES

		log "Installation completed."
	else
		log "Installation cancelled."
	fi
}

# main
case "$1" in
	help)
		show_usage
		;;
	sync)
		sync
		;;
	push)
		push
		;;
	both)
		both
		;;
	list)
		list
		;;
	fix)
		fix
		;;
	install)
		install
		;;
	*)
		show_usage
		;;
esac
