#!/usr/bin/env sh

# --- USER PREFERENCES ---

# Default Apps
export EDITOR=helix
export BROWSER=firefox

TERM_WAYLAND=foot
TERM_X11=alacritty

# Sort Preference
export LC_COLLATE=C

# --- DIRECTORIES ---

# User PATH
export PATH="$HOME/.local/bin:$PATH"

# Clear HOME
if command -v antidot &> /dev/null; then
	eval "$(antidot init -s bash)"
fi

rm -f .xsession-errors .xsession-errors.old .dmrc .Xauthority

# --- DESKTOP-SESSION ---

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	export TERM=$TERM_WAYLAND

	if [ "$DESKTOP_SESSION" = "sway" ]; then
		export XDG_CURRENT_DESKTOP="sway"
	fi

elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
	export TERM=$TERM_X11
fi
